name: Publish wheels

on:
  push:
    # TODO: remove eventually
    branches-ignore:
      - '*'
#    tags:
#      - '*'
    paths-ignore:
      - '*.md'
#  pull_request:
#    branches:
#      - 'main'
#    paths-ignore:
#      - '*.md'

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Conan
      id: cache-conan
      uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      with:
        path: |
          conan_data
        key: conan-${{ matrix.os }}-${{ hashFiles('conanfile.txt') }}

    - name: Set up Python ${{ matrix.python_version }} for conan
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install conan for Windows
      run: |
        pip install pip --upgrade
        pip install conan
        conan profile new default --detect
        conan profile update "settings.compiler=Visual Studio" default
        conan profile update "settings.compiler.version=16" default
        conan config set "storage.path=$env:GITHUB_WORKSPACE/conan_data"
        conan install --install-folder $PWD/conan_build --remote conancenter lib/valhalla

    - uses: pypa/cibuildwheel@v2.3.1
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.9

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl

  upload_all:
    name: Upload if release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2

    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: jonathf
        password: ${{ secrets.pypi_password }}
