name: Test code

on:
  push:
    # TODO: change back to main
    branches:
      - '*'
    paths-ignore:
      - '*.md'
#  pull_request:
#    branches:
#      - 'main'
#    paths-ignore:
#      - '*.md'

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        # TODO: re-enable other OSs
        include:
#          - image: ubuntu-latest
#            platform: linux
#            cxx: 'g++-9'
          - image: windows-latest
            platform: windows
            cxx: 'Visual Studio'
          # - macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Conan
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/conan_data
          ${{ github.workspace }}/conan_build
        key: conan-${{ matrix.platform }}-${{ hashFiles('lib/valhalla/conanfile.txt') }}

    - name: Cache Valhalla
      id: cache-valhalla
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/lib/valhalla/build
        key: valhalla-${{ matrix.platform }}

#    - name: Cache Win deps
#      id: win-deps
#      uses: actions/cache@v2
#      with:
#        path: |
#          c:/vcpkg
#        key: win-deps-${{ hashFiles('lib/valhalla/.vcpkg_deps.txt') }}

    - uses: pypa/cibuildwheel@v2.3.1
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.9
        CIBW_BUILD: '*cp310*'

    - name: TEMP
      run: |
        ls -la lib/valhalla/build

#    - name: Verify clean directory
#      run: git diff --exit-code
#      shell: bash
