name: Test code

on:
  push:
    # TODO: change back to main
    branches:
      - '*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: re-enable other OSs
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Conan
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: |
          conan_data
        key: conan-${{ matrix.os }}-${{ hashFiles('conanfile.txt') }}

    - name: Set up Python for conan
      uses: actions/setup-python@v2
      if: steps.cache-conan.outputs.cache-hit != 'true'
      with:
        python-version: '3.x'

    - name: Install conan dependencies
      if: steps.cache-conan.outputs.cache-hit != 'true'
      run: |
        pip install pip --upgrade
        pip install conan
        conan profile new default --detect
        conan profile update "settings.compiler=Visual Studio" default
        conan profile update "settings.compiler.version=16" default
        conan config set "storage.path=$env:GITHUB_WORKSPACE/conan_data"
        conan install --install-folder $PWD/conan_build --remote conancenter lib/valhalla

    - name: Cache Valhalla
      id: cache-valhalla
      uses: actions/cache@v2
      with:
        path: |
          lib/valhalla/build
        key: valhalla-${{ matrix.os }}

    - name: Build Valhalla
      run: |
        cmake -B lib/valhalla/build -S lib/valhalla -DENABLE_BENCHMARKS=OFF -DENABLE_PYTHON_BINDINGS=ON -DENABLE_TESTS=OFF -DENABLE_TOOLS=OFF -DENABLE_SERVICES=OFF -DENABLE_HTTP=OFF -DCMAKE_BUILD_TYPE=Release
        cmake --build lib/valhalla/build -- -j$(nproc)
      shell: bash

    - uses: pypa/cibuildwheel@v2.3.1
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.9
        CIBW_BUILD: '*cp310*'

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash
